name: Crash
description: Report a fatal crash that resulted in Olive unexpectedly closing.
title: '[CRASH] '
labels:
  - Crash
  - Triage
body:
  - type: input
    id: commit_hash
    attributes:
      label: Commit hash
      description: |
        This 8 character string of letters/numbers unique identifies the exact version you are using.
        You can find it in title bar or in the Help > About dialog
      placeholder: e.g. 3ea173c9
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: Your operating system and version.
      placeholder: e.g. Windows 10, Ubuntu 20.04, or macOS 10.15
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: Provide a clear and concise description of how Olive crashed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1. 
        2. 
        3. 
  - type: textarea
    attributes:
      label: Additional information
      value: |
        <details><summary><strong>Crash Report</strong></summary><pre><code>

        <!-- You should have received a crash report from Olive to paste here. -->

        </code></pre></details>
