name: Crash
description: Report a fatal crash that resulted in Olive unexpectedly closing.
labels:
  - bug
  - wontfix
body:
  - type: input
    id: assignees
    attributes:
      label: Assignees
      description: Does this collide with the `assignees` query param?
  - type: input
    id: template
    attributes:
      label: Template
      description: Does this collide with the `template` query param?
  - type: input
    id: commit_hash
    attributes:
      label: Commit hash
      description: |
        This 8 character string of letters/numbers unique identifies the exact version you are using.
        You can find it in title bar or in the `Help` > `About` dialog
      placeholder: e.g. 3ea173c9
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: Your operating system and version.
      placeholder: e.g. Windows 10, Ubuntu 20.04, or macOS 10.15
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Source
      description: How did you obtain Olive?
      options:
        - Official AppImage
        - Third-party download
        - Built from source
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: Provide a clear and concise description of how Olive crashed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |-
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: You can add console output, crash reports, and comments here.
      value: |

        <details><summary><strong>Crash Report</strong></summary><pre><code>

        <!-- You should have received a crash report from Olive to paste here. -->

        </code></pre></details>
