name: Context

on:
  push:
    branches:
      - master

jobs:
  print-contexts:
    name: Print Contexts
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: printenv
        run: printenv
      - name: github
        env:
          GITHUB: ${{ toJSON(github) }}
        run: echo "$GITHUB"
      - name: env
        env:
          ENV: ${{ toJSON(env) }}
        run: echo "$ENV"
      - name: job
        env:
          JOB: ${{ toJSON(job) }}
        run: echo "$JOB"
      - name: steps
        env:
          STEPS: ${{ toJSON(steps) }}
        run: echo "$STEPS"
      - name: runner
        env:
          RUNNER: ${{ toJSON(runner) }}
        run: echo "$RUNNER"
      - name: strategy
        env:
          STRATEGY: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY"
      - name: secrets
        env:
          SECRETS: ${{ toJSON(secrets) }}
        run: echo "$SECRETS"
      - name: matrix
        env:
          MATRIX: ${{ toJSON(matrix) }}
        run: echo "$MATRIX"
