name: Issue Test

on:
  issue_comment

jobs:
  issue-commented:
    name: Issue commented
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event
        run: |
          cat <<EOF
            ${{ toJSON(github.event) }}
          EOF
