name: Paths Filter
on:
  push:
    branches:
      - master
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            testfile: test.txt
  build:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Print changes
        env:
          CHANGES: ${{ needs.changes.outputs.packages }}
        run: |
          echo "$CHANGES"
          echo "Parses to empty array? ${{ fromJSON(needs.changes.outputs.packages) == fromJSON('[]') }}"
          echo "Is empty array string? ${{ needs.changes.outputs.packages == '[]' }}"
