name: PR Approval

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Self-approve
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'Simran-B'
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            try {
              const result = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 999, //context.issue.number, // context.payload.pull_request.number ?
                event: "APPROVE"
              })
              console.log(result.status)
            } catch(err) {
              console.log(err.message)
              process.exit(1)
            }
