name: Secrets

on:
  push:
    branches:
      - master

jobs:
  env-secret:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: |
          npm install -g tweetsodium
      - uses: actions/github-script@v4
        with:
          script: |
            const sodium = require('tweetsodium');

            const envName = "prod"
            const secretName = "MY_SECRET"
            const value = "New secret value";

            const key = await github.actions.getEnvironmentPublicKey({
              repository_id: context.repo.id,
              environment_name: envName,
            })

            const messageBytes = Buffer.from(value);
            const keyBytes = Buffer.from(key, "base64");
            const encryptedBytes = sodium.seal(messageBytes, keyBytes);
            const encrypted = Buffer.from(encryptedBytes).toString("base64");
            
            const result = await github.actions.createOrUpdateEnvironmentSecret({
              repository_id: context.repo.id,
              environment_name, envName,
              secret_name: secretName,
              encrypted_value: encrypted,
            })
